# Generated by Django 4.2.7 on 2025-10-31 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(db_index=True, max_length=255)),
                ('name_te', models.CharField(blank=True, max_length=255, null=True)),
                ('brand', models.CharField(blank=True, max_length=255, null=True)),
                ('form', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'medicines',
            },
        ),
    ]
